# .github/workflows/daily-stock-analysis.yml
name: Daily Stock Analysis

on:
  schedule:
    # Runs at 10:00 AM UTC every day. Adjust as needed.
    # Check cron syntax: https://crontab.guru/
    - cron: '0 10 * * *'
  workflow_dispatch:
    # Allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  run_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Or any other suitable version like '3.10', '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run stock analysis script
      run: python stock_alerter.py
      env:
        # Use a GitHub secret for your Discord webhook URL
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

